### ISSUE TITLE
Can i add build for riscv64?

### ISSUE THREAD

**Issue by luyahan** [microsoft/ripgrep-prebuilt#10]

**Comment by luyahan** [comment]
Can i add build for riscv64?

**Comment by roblourens** [comment]
Why?

**Comment by luyahan** [comment]
> Why?

Chromium on riscv64 has been build pass. So we want to try build vscode on riscv64.

**Comment by roblourens** [comment]
Sorry, I don't want to support architectures that vscode doesn't support. You can do a local build and plug that in to your vscode build.

**Comment by balupton** [comment]
@luyahan I'm thinking of forking this repo and making it a builder of as many rust deps as people want compiled. How did you plan to add riscv support considering that github actions does not support it yet?
